### ISSUE TITLE
BUG#PRODUCCION-ERROR-IMPORTACION EXCEL-COMPRAS-URGENTE

### ISSUE THREAD

**Issue by EDITHYALLI** [Intel-IT/IITIssues#540]
### Software

Contabilidad Escritorio

### Descripción.

No procesa el formato de Compras  diciembre 2023-menciona error de cuentas adjunto  la imagen 
y backupmpara su revisiom ya se valido todo
![image](https://github.com/Intel-IT/IITIssues/assets/124917960/dc4ff282-0d63-45bd-8629-fd326ef230ed)

![image](https://github.com/Intel-IT/IITIssues/assets/124917960/81944fdc-0aae-49bc-b2c0-c6cfa7a4ae4f)

### Pasos para reproducir el comportamiento

1.Herramientas 
2.importra desde excel ,
3. rellenas 8 selecciones el archivo ultima fila 248 proceso 
4. luego me sale el mensaje de error no procesa

### Comportamiento esperado

*procesar con exito el registro de compras y ventas

### Screenshots - Media

![image](https://github.com/Intel-IT/IITIssues/assets/124917960/37320208-bea2-48dc-9341-64c4a8b99500)

![image](https://github.com/Intel-IT/IITIssues/assets/124917960/02dec625-79b3-4723-a2fd-a825a8e2f010)

### Copia de la base de datos

https://drive.google.com/file/d/1EQTEkl3t7kQE0R6CuVgpyMJy6G1E4lZY/view?usp=drivesdk

**Comment by EDITHYALLI** [comment]
CONRASEÑA:70990736
https://docs.google.com/spreadsheets/d/1ZJtafxo1Gjdjd8n5AaliaEcC9rCmJ_p1/edit?usp=sharing&ouid=117180474802963414772&rtpof=true&sd=true

**Comment by Skeyss** [comment]
Errores en los formatos de las celdas
