### ISSUE TITLE
BUG#PRODUCCION previsualizacion de impresion con peso sale #Error

### ISSUE THREAD

**Issue by emeneses19** [Intel-IT/IITIssues#588]
### Software

Facturador Escritorio

### Descripción.

al previsualizar en el PDF, se muetsra comoen la imagen 
![image](https://github.com/Intel-IT/IITIssues/assets/55803540/bac18731-86ff-4d52-9ac3-8868457c9854)

### Pasos para reproducir el comportamiento

1. Crear un producto con peso
2. Emitir comprobante 
3. Usar el formato de impresion ->https://drive.google.com/file/d/13H9W0l0_UqqdrpPlKL5jSAhx7K2ki87l/view?usp=sharing
4. Previsualizar el comrpobante

### Comportamiento esperado

Al previsualizar debe mostrar el peso sumado de los items

**Comment by Skeyss** [comment]
Todo Correcto solo era un error en la expresion del campo
